/**
 * LE VAN DO® OKX 原生交易机器人 — PM2 进程管理配置
 *
 * 使用方式:
 *   pm2 start ecosystem.config.js           # 启动（默认模拟模式）
 *   pm2 start ecosystem.config.js --env production  # 实盘
 *   pm2 stop le-van-do-bot
 *   pm2 logs le-van-do-bot
 *   pm2 restart le-van-do-bot
 */
module.exports = {
    apps: [
        {
            name: 'le-van-do-bot',
            script: 'bot.py',
            cwd: __dirname,
            interpreter: '/usr/bin/python3',
            exec_mode: 'fork',
            instances: 1,
            autorestart: true,
            watch: false,
            max_memory_restart: '200M',
            restart_delay: 5000,
            max_restarts: 10,
            exp_backoff_restart_delay: 100,

            // 环境变量（默认：测试网 / 模擬盤真實下單）
            env: {
                NODE_ENV: 'development',
                PYTHONUNBUFFERED: '1',
                EXCHANGE_NETWORK: 'testnet',
                DRY_RUN: 'false',
                LOG_LEVEL: 'INFO',
                SETUP_TYPE: 'Open/Close',
                TPS_TYPE: 'Trailing',
                SIDEWAYS_FILTER: 'No Filtering',
                TRADING_SYMBOLS: '0G-USDT-SWAP,1INCH-USDT-SWAP,2Z-USDT-SWAP,A-USDT-SWAP,AAOI-USDT-SWAP,AAPL-USDT-SWAP,AAVE-USDT-SWAP,ACH-USDT-SWAP,ACT-USDT-SWAP,ACU-USDT-SWAP,ADA-USDT-SWAP,ADBE-USDT-SWAP,AERO-USDT-SWAP,AEVO-USDT-SWAP,AGLD-USDT-SWAP,AI-USDT-SWAP,AIXBT-USDT-SWAP,ALAB-USDT-SWAP,ALGO-USDT-SWAP,ALLO-USDT-SWAP,AMAT-USDT-SWAP,AMD-USDT-SWAP,AMZN-USDT-SWAP,ANIME-USDT-SWAP,ANTHROPIC-USDT-SWAP,APE-USDT-SWAP,API3-USDT-SWAP,APLD-USDT-SWAP,APP-USDT-SWAP,APR-USDT-SWAP,APT-USDT-SWAP,AR-USDT-SWAP,ARB-USDT-SWAP,ARKM-USDT-SWAP,ARM-USDT-SWAP,ARX-USDT-SWAP,ASML-USDT-SWAP,ASTER-USDT-SWAP,ASTS-USDT-SWAP,AT-USDT-SWAP,ATH-USDT-SWAP,ATOM-USDT-SWAP,AUCTION-USDT-SWAP,AVAX-USDT-SWAP,AVGO-USDT-SWAP,AVNT-USDT-SWAP,AXS-USDT-SWAP,AXTI-USDT-SWAP,AZTEC-USDT-SWAP,BABY-USDT-SWAP,BAND-USDT-SWAP,BARD-USDT-SWAP,BASED-USDT-SWAP,BAT-USDT-SWAP,BB-USDT-SWAP,BCH-USDT-SWAP,BE-USDT-SWAP,BEAT-USDT-SWAP,BERA-USDT-SWAP,BICO-USDT-SWAP,BIGTIME-USDT-SWAP,BILL-USDT-SWAP,BIO-USDT-SWAP,BLEND-USDT-SWAP,BLUR-USDT-SWAP,BMNR-USDT-SWAP,BNB-USDT-SWAP,BOME-USDT-SWAP,BONK-USDT-SWAP,BOT-USDT-SWAP,BRETT-USDT-SWAP,BREV-USDT-SWAP,BSB-USDT-SWAP,BSP-USDT-SWAP,BTC-USDT-SWAP,BX-USDT-SWAP,BZ-USDT-SWAP,CAP-USDT-SWAP,CBRS-USDT-SWAP,CC-USDT-SWAP,CELO-USDT-SWAP,CFX-USDT-SWAP,CGNX-USDT-SWAP,CHIP-USDT-SWAP,CHZ-USDT-SWAP,CIEN-USDT-SWAP,CL-USDT-SWAP,COAI-USDT-SWAP,COHR-USDT-SWAP,COIN-USDT-SWAP,COMP-USDT-SWAP,CORE-USDT-SWAP,COST-USDT-SWAP,CRCL-USDT-SWAP,CRDO-USDT-SWAP,CRO-USDT-SWAP,CRV-USDT-SWAP,CRWD-USDT-SWAP,CRWV-USDT-SWAP,CSCO-USDT-SWAP,CVX-USDT-SWAP,DASH-USDT-SWAP,DATA-USDT-SWAP,DELL-USDT-SWAP,DKNG-USDT-SWAP,DOGE-USDT-SWAP,DOOD-USDT-SWAP,DOT-USDT-SWAP,DRAM-USDT-SWAP,DYDX-USDT-SWAP,EDEN-USDT-SWAP,EDGE-USDT-SWAP,EGLD-USDT-SWAP,EIGEN-USDT-SWAP,ENA-USDT-SWAP,ENJ-USDT-SWAP,ENS-USDT-SWAP,ENSO-USDT-SWAP,ESP-USDT-SWAP,ETC-USDT-SWAP,ETH-USDT-SWAP,ETHFI-USDT-SWAP,ETHW-USDT-SWAP,EWJ-USDT-SWAP,EWT-USDT-SWAP,EWY-USDT-SWAP,EWZ-USDT-SWAP,F-USDT-SWAP,FARTCOIN-USDT-SWAP,FIL-USDT-SWAP,FLNC-USDT-SWAP,FLOKI-USDT-SWAP,FLOW-USDT-SWAP,FOGO-USDT-SWAP,GALA-USDT-SWAP,GAS-USDT-SWAP,GEV-USDT-SWAP,GIGGLE-USDT-SWAP,GLM-USDT-SWAP,GLW-USDT-SWAP,GME-USDT-SWAP,GMT-USDT-SWAP,GMX-USDT-SWAP,GOOGL-USDT-SWAP,GPS-USDT-SWAP,GRAM-USDT-SWAP,GRASS-USDT-SWAP,GRT-USDT-SWAP,H-USDT-SWAP,HBAR-USDT-SWAP,HIMS-USDT-SWAP,HMSTR-USDT-SWAP,HOME-USDT-SWAP,HOOD-USDT-SWAP,HPE-USDT-SWAP,HUMA-USDT-SWAP,HYPE-USDT-SWAP,HYUNDAI-USDT-SWAP,IBM-USDT-SWAP,ICP-USDT-SWAP,ICX-USDT-SWAP,IMX-USDT-SWAP,INFQ-USDT-SWAP,INIT-USDT-SWAP,INJ-USDT-SWAP,INTC-USDT-SWAP,IOST-USDT-SWAP,IOTA-USDT-SWAP,IREN-USDT-SWAP,IRYS-USDT-SWAP,ISRG-USDT-SWAP,IWM-USDT-SWAP,JELLYJELLY-USDT-SWAP,JNJ-USDT-SWAP,JTO-USDT-SWAP,JUP-USDT-SWAP,KAITO-USDT-SWAP,KAT-USDT-SWAP,KGEN-USDT-SWAP,KIOXIA-USDT-SWAP,KITE-USDT-SWAP,KLAC-USDT-SWAP,KMNO-USDT-SWAP,KORU-USDT-SWAP,KSM-USDT-SWAP,LA-USDT-SWAP,LAB-USDT-SWAP,LAYER-USDT-SWAP,LDO-USDT-SWAP,LIGHT-USDT-SWAP,LINEA-USDT-SWAP,LINK-USDT-SWAP,LIT-USDT-SWAP,LITE-USDT-SWAP,LLY-USDT-SWAP,LPT-USDT-SWAP,LQTY-USDT-SWAP,LRCX-USDT-SWAP,LTC-USDT-SWAP,LUNA-USDT-SWAP,LUNR-USDT-SWAP,MAGIC-USDT-SWAP,MANA-USDT-SWAP,MASK-USDT-SWAP,ME-USDT-SWAP,MEGA-USDT-SWAP,MEME-USDT-SWAP,MERL-USDT-SWAP,MET-USDT-SWAP,META-USDT-SWAP,METIS-USDT-SWAP,MEW-USDT-SWAP,MINA-USDT-SWAP,MINIMAX-USDT-SWAP,MMT-USDT-SWAP,MON-USDT-SWAP,MOODENG-USDT-SWAP,MORPHO-USDT-SWAP,MOVE-USDT-SWAP,MRVL-USDT-SWAP,MSFT-USDT-SWAP,MSTR-USDT-SWAP,MU-USDT-SWAP,MUBARAK-USDT-SWAP,MUU-USDT-SWAP,MVLL-USDT-SWAP,NBIS-USDT-SWAP,NEAR-USDT-SWAP,NEIRO-USDT-SWAP,NEO-USDT-SWAP,NES-USDT-SWAP,NFLX-USDT-SWAP,NG-USDT-SWAP,NIGHT-USDT-SWAP,NMR-USDT-SWAP,NOK-USDT-SWAP,NOT-USDT-SWAP,NOW-USDT-SWAP,NVDA-USDT-SWAP,O-USDT-SWAP,OFC-USDT-SWAP,OKB-USDT-SWAP,OL-USDT-SWAP,ON-USDT-SWAP,ONDO-USDT-SWAP,ONDS-USDT-SWAP,ONE-USDT-SWAP,ONT-USDT-SWAP,OP-USDT-SWAP,OPENAI-USDT-SWAP,OPG-USDT-SWAP,OPN-USDT-SWAP,ORCL-USDT-SWAP,ORDER-USDT-SWAP,ORDI-USDT-SWAP,OSCR-USDT-SWAP,PARTI-USDT-SWAP,PENDLE-USDT-SWAP,PENG-USDT-SWAP,PENGU-USDT-SWAP,PEOPLE-USDT-SWAP,PEPE-USDT-SWAP,PI-USDT-SWAP,PIEVERSE-USDT-SWAP,PIPPIN-USDT-SWAP,PLTR-USDT-SWAP,PLUME-USDT-SWAP,PNUT-USDT-SWAP,POET-USDT-SWAP,POL-USDT-SWAP,POPCAT-USDT-SWAP,PROS-USDT-SWAP,PROVE-USDT-SWAP,PUMP-USDT-SWAP,PYTH-USDT-SWAP,QCOM-USDT-SWAP,QNT-USDT-SWAP,QQQ-USDT-SWAP,QTUM-USDT-SWAP,RAM-USDT-SWAP,RAVE-USDT-SWAP,RAY-USDT-SWAP,RDDT-USDT-SWAP,RDW-USDT-SWAP,RE-USDT-SWAP,RECALL-USDT-SWAP,RENDER-USDT-SWAP,RESOLV-USDT-SWAP,RIVER-USDT-SWAP,RIVN-USDT-SWAP,RKLB-USDT-SWAP,RLS-USDT-SWAP,ROBO-USDT-SWAP,ROK-USDT-SWAP,RSR-USDT-SWAP,RVN-USDT-SWAP,S-USDT-SWAP,SAHARA-USDT-SWAP,SAMSUNG-USDT-SWAP,SAND-USDT-SWAP,SAPIEN-USDT-SWAP,SATS-USDT-SWAP,SEI-USDT-SWAP,SENT-USDT-SWAP,SHAZ-USDT-SWAP,SHELL-USDT-SWAP,SHIB-USDT-SWAP,SHLD-USDT-SWAP,SIGN-USDT-SWAP,SIMO-USDT-SWAP,SKHY-USDT-SWAP,SKHYNIX-USDT-SWAP,SKY-USDT-SWAP,SLX-USDT-SWAP,SMCI-USDT-SWAP,SMH-USDT-SWAP,SNDK-USDT-SWAP,SNOW-USDT-SWAP,SNX-USDT-SWAP,SNXX-USDT-SWAP,SOFTBANK-USDT-SWAP,SOL-USDT-SWAP,SONY-USDT-SWAP,SOON-USDT-SWAP,SOPH-USDT-SWAP,SOXL-USDT-SWAP,SOXS-USDT-SWAP,SPACE-USDT-SWAP,SPCX-USDT-SWAP,SPK-USDT-SWAP,SPX-USDT-SWAP,SPY-USDT-SWAP,SQQQ-USDT-SWAP,SSV-USDT-SWAP,STABLE-USDT-SWAP,STRC-USDT-SWAP,STRK-USDT-SWAP,STX-USDT-SWAP,SUI-USDT-SWAP,SUSHI-USDT-SWAP,SYRUP-USDT-SWAP,TAO-USDT-SWAP,TER-USDT-SWAP,THETA-USDT-SWAP,TIA-USDT-SWAP,TQQQ-USDT-SWAP,TRB-USDT-SWAP,TRIA-USDT-SWAP,TRUMP-USDT-SWAP,TRUST-USDT-SWAP,TRUTH-USDT-SWAP,TRX-USDT-SWAP,TSEM-USDT-SWAP,TSLA-USDT-SWAP,TSM-USDT-SWAP,TTMI-USDT-SWAP,TTWO-USDT-SWAP,TURBO-USDT-SWAP,TWLO-USDT-SWAP,UB-USDT-SWAP,UMA-USDT-SWAP,UNH-USDT-SWAP,UNI-USDT-SWAP,UP-USDT-SWAP,URNM-USDT-SWAP,USAR-USDT-SWAP,USDC-USDT-SWAP,USELESS-USDT-SWAP,USO-USDT-SWAP,UVXY-USDT-SWAP,VANA-USDT-SWAP,VIRTUAL-USDT-SWAP,VRT-USDT-SWAP,VVV-USDT-SWAP,W-USDT-SWAP,WAL-USDT-SWAP,WCT-USDT-SWAP,WDC-USDT-SWAP,WEN-USDT-SWAP,WET-USDT-SWAP,WIF-USDT-SWAP,WLD-USDT-SWAP,WLFI-USDT-SWAP,WOO-USDT-SWAP,XAG-USDT-SWAP,XAU-USDT-SWAP,XBI-USDT-SWAP,XCU-USDT-SWAP,XLE-USDT-SWAP,XLM-USDT-SWAP,XPD-USDT-SWAP,XPL-USDT-SWAP,XPT-USDT-SWAP,XRP-USDT-SWAP,XTZ-USDT-SWAP,YB-USDT-SWAP,YFI-USDT-SWAP,YGG-USDT-SWAP,ZAMA-USDT-SWAP,ZBT-USDT-SWAP,ZEC-USDT-SWAP,ZEN-USDT-SWAP,ZETA-USDT-SWAP,ZHIPU-USDT-SWAP,ZIL-USDT-SWAP,ZK-USDT-SWAP,ZKP-USDT-SWAP,ZM-USDT-SWAP,ZORA-USDT-SWAP,ZRO-USDT-SWAP,ZRX-USDT-SWAP',
                BASE_TIMEFRAME_MIN: '15',
                TF_MULT: '18',
                INITIAL_CAPITAL: '253576',
                DEFAULT_LEVERAGE: '100',
                TRADE_QTY_PCT: '0.001',
                OKX_API_KEY: '92594391-3d2a-407e-9cab-bee6e8d8f4c2',
                OKX_API_SECRET: '4B9B31851E3F81B329AB2E9BB8F26E95',
                OKX_API_PASSPHRASE: 'Ya@65237365',
            },

            // 实盘环境（使用 --env production）
            env_production: {
                NODE_ENV: 'production',
                PYTHONUNBUFFERED: '1',
                EXCHANGE_NETWORK: 'production',
                DRY_RUN: 'false',
                LOG_LEVEL: 'INFO',
                SETUP_TYPE: 'Open/Close',
                TPS_TYPE: 'Trailing',
                SIDEWAYS_FILTER: 'No Filtering',
                TRADING_SYMBOLS: '0G-USDT-SWAP,1INCH-USDT-SWAP,2Z-USDT-SWAP,A-USDT-SWAP,AAOI-USDT-SWAP,AAPL-USDT-SWAP,AAVE-USDT-SWAP,ACH-USDT-SWAP,ACT-USDT-SWAP,ACU-USDT-SWAP,ADA-USDT-SWAP,ADBE-USDT-SWAP,AERO-USDT-SWAP,AEVO-USDT-SWAP,AGLD-USDT-SWAP,AI-USDT-SWAP,AIXBT-USDT-SWAP,ALAB-USDT-SWAP,ALGO-USDT-SWAP,ALLO-USDT-SWAP,AMAT-USDT-SWAP,AMD-USDT-SWAP,AMZN-USDT-SWAP,ANIME-USDT-SWAP,ANTHROPIC-USDT-SWAP,APE-USDT-SWAP,API3-USDT-SWAP,APLD-USDT-SWAP,APP-USDT-SWAP,APR-USDT-SWAP,APT-USDT-SWAP,AR-USDT-SWAP,ARB-USDT-SWAP,ARKM-USDT-SWAP,ARM-USDT-SWAP,ARX-USDT-SWAP,ASML-USDT-SWAP,ASTER-USDT-SWAP,ASTS-USDT-SWAP,AT-USDT-SWAP,ATH-USDT-SWAP,ATOM-USDT-SWAP,AUCTION-USDT-SWAP,AVAX-USDT-SWAP,AVGO-USDT-SWAP,AVNT-USDT-SWAP,AXS-USDT-SWAP,AXTI-USDT-SWAP,AZTEC-USDT-SWAP,BABY-USDT-SWAP,BAND-USDT-SWAP,BARD-USDT-SWAP,BASED-USDT-SWAP,BAT-USDT-SWAP,BB-USDT-SWAP,BCH-USDT-SWAP,BE-USDT-SWAP,BEAT-USDT-SWAP,BERA-USDT-SWAP,BICO-USDT-SWAP,BIGTIME-USDT-SWAP,BILL-USDT-SWAP,BIO-USDT-SWAP,BLEND-USDT-SWAP,BLUR-USDT-SWAP,BMNR-USDT-SWAP,BNB-USDT-SWAP,BOME-USDT-SWAP,BONK-USDT-SWAP,BOT-USDT-SWAP,BRETT-USDT-SWAP,BREV-USDT-SWAP,BSB-USDT-SWAP,BSP-USDT-SWAP,BTC-USDT-SWAP,BX-USDT-SWAP,BZ-USDT-SWAP,CAP-USDT-SWAP,CBRS-USDT-SWAP,CC-USDT-SWAP,CELO-USDT-SWAP,CFX-USDT-SWAP,CGNX-USDT-SWAP,CHIP-USDT-SWAP,CHZ-USDT-SWAP,CIEN-USDT-SWAP,CL-USDT-SWAP,COAI-USDT-SWAP,COHR-USDT-SWAP,COIN-USDT-SWAP,COMP-USDT-SWAP,CORE-USDT-SWAP,COST-USDT-SWAP,CRCL-USDT-SWAP,CRDO-USDT-SWAP,CRO-USDT-SWAP,CRV-USDT-SWAP,CRWD-USDT-SWAP,CRWV-USDT-SWAP,CSCO-USDT-SWAP,CVX-USDT-SWAP,DASH-USDT-SWAP,DATA-USDT-SWAP,DELL-USDT-SWAP,DKNG-USDT-SWAP,DOGE-USDT-SWAP,DOOD-USDT-SWAP,DOT-USDT-SWAP,DRAM-USDT-SWAP,DYDX-USDT-SWAP,EDEN-USDT-SWAP,EDGE-USDT-SWAP,EGLD-USDT-SWAP,EIGEN-USDT-SWAP,ENA-USDT-SWAP,ENJ-USDT-SWAP,ENS-USDT-SWAP,ENSO-USDT-SWAP,ESP-USDT-SWAP,ETC-USDT-SWAP,ETH-USDT-SWAP,ETHFI-USDT-SWAP,ETHW-USDT-SWAP,EWJ-USDT-SWAP,EWT-USDT-SWAP,EWY-USDT-SWAP,EWZ-USDT-SWAP,F-USDT-SWAP,FARTCOIN-USDT-SWAP,FIL-USDT-SWAP,FLNC-USDT-SWAP,FLOKI-USDT-SWAP,FLOW-USDT-SWAP,FOGO-USDT-SWAP,GALA-USDT-SWAP,GAS-USDT-SWAP,GEV-USDT-SWAP,GIGGLE-USDT-SWAP,GLM-USDT-SWAP,GLW-USDT-SWAP,GME-USDT-SWAP,GMT-USDT-SWAP,GMX-USDT-SWAP,GOOGL-USDT-SWAP,GPS-USDT-SWAP,GRAM-USDT-SWAP,GRASS-USDT-SWAP,GRT-USDT-SWAP,H-USDT-SWAP,HBAR-USDT-SWAP,HIMS-USDT-SWAP,HMSTR-USDT-SWAP,HOME-USDT-SWAP,HOOD-USDT-SWAP,HPE-USDT-SWAP,HUMA-USDT-SWAP,HYPE-USDT-SWAP,HYUNDAI-USDT-SWAP,IBM-USDT-SWAP,ICP-USDT-SWAP,ICX-USDT-SWAP,IMX-USDT-SWAP,INFQ-USDT-SWAP,INIT-USDT-SWAP,INJ-USDT-SWAP,INTC-USDT-SWAP,IOST-USDT-SWAP,IOTA-USDT-SWAP,IREN-USDT-SWAP,IRYS-USDT-SWAP,ISRG-USDT-SWAP,IWM-USDT-SWAP,JELLYJELLY-USDT-SWAP,JNJ-USDT-SWAP,JTO-USDT-SWAP,JUP-USDT-SWAP,KAITO-USDT-SWAP,KAT-USDT-SWAP,KGEN-USDT-SWAP,KIOXIA-USDT-SWAP,KITE-USDT-SWAP,KLAC-USDT-SWAP,KMNO-USDT-SWAP,KORU-USDT-SWAP,KSM-USDT-SWAP,LA-USDT-SWAP,LAB-USDT-SWAP,LAYER-USDT-SWAP,LDO-USDT-SWAP,LIGHT-USDT-SWAP,LINEA-USDT-SWAP,LINK-USDT-SWAP,LIT-USDT-SWAP,LITE-USDT-SWAP,LLY-USDT-SWAP,LPT-USDT-SWAP,LQTY-USDT-SWAP,LRCX-USDT-SWAP,LTC-USDT-SWAP,LUNA-USDT-SWAP,LUNR-USDT-SWAP,MAGIC-USDT-SWAP,MANA-USDT-SWAP,MASK-USDT-SWAP,ME-USDT-SWAP,MEGA-USDT-SWAP,MEME-USDT-SWAP,MERL-USDT-SWAP,MET-USDT-SWAP,META-USDT-SWAP,METIS-USDT-SWAP,MEW-USDT-SWAP,MINA-USDT-SWAP,MINIMAX-USDT-SWAP,MMT-USDT-SWAP,MON-USDT-SWAP,MOODENG-USDT-SWAP,MORPHO-USDT-SWAP,MOVE-USDT-SWAP,MRVL-USDT-SWAP,MSFT-USDT-SWAP,MSTR-USDT-SWAP,MU-USDT-SWAP,MUBARAK-USDT-SWAP,MUU-USDT-SWAP,MVLL-USDT-SWAP,NBIS-USDT-SWAP,NEAR-USDT-SWAP,NEIRO-USDT-SWAP,NEO-USDT-SWAP,NES-USDT-SWAP,NFLX-USDT-SWAP,NG-USDT-SWAP,NIGHT-USDT-SWAP,NMR-USDT-SWAP,NOK-USDT-SWAP,NOT-USDT-SWAP,NOW-USDT-SWAP,NVDA-USDT-SWAP,O-USDT-SWAP,OFC-USDT-SWAP,OKB-USDT-SWAP,OL-USDT-SWAP,ON-USDT-SWAP,ONDO-USDT-SWAP,ONDS-USDT-SWAP,ONE-USDT-SWAP,ONT-USDT-SWAP,OP-USDT-SWAP,OPENAI-USDT-SWAP,OPG-USDT-SWAP,OPN-USDT-SWAP,ORCL-USDT-SWAP,ORDER-USDT-SWAP,ORDI-USDT-SWAP,OSCR-USDT-SWAP,PARTI-USDT-SWAP,PENDLE-USDT-SWAP,PENG-USDT-SWAP,PENGU-USDT-SWAP,PEOPLE-USDT-SWAP,PEPE-USDT-SWAP,PI-USDT-SWAP,PIEVERSE-USDT-SWAP,PIPPIN-USDT-SWAP,PLTR-USDT-SWAP,PLUME-USDT-SWAP,PNUT-USDT-SWAP,POET-USDT-SWAP,POL-USDT-SWAP,POPCAT-USDT-SWAP,PROS-USDT-SWAP,PROVE-USDT-SWAP,PUMP-USDT-SWAP,PYTH-USDT-SWAP,QCOM-USDT-SWAP,QNT-USDT-SWAP,QQQ-USDT-SWAP,QTUM-USDT-SWAP,RAM-USDT-SWAP,RAVE-USDT-SWAP,RAY-USDT-SWAP,RDDT-USDT-SWAP,RDW-USDT-SWAP,RE-USDT-SWAP,RECALL-USDT-SWAP,RENDER-USDT-SWAP,RESOLV-USDT-SWAP,RIVER-USDT-SWAP,RIVN-USDT-SWAP,RKLB-USDT-SWAP,RLS-USDT-SWAP,ROBO-USDT-SWAP,ROK-USDT-SWAP,RSR-USDT-SWAP,RVN-USDT-SWAP,S-USDT-SWAP,SAHARA-USDT-SWAP,SAMSUNG-USDT-SWAP,SAND-USDT-SWAP,SAPIEN-USDT-SWAP,SATS-USDT-SWAP,SEI-USDT-SWAP,SENT-USDT-SWAP,SHAZ-USDT-SWAP,SHELL-USDT-SWAP,SHIB-USDT-SWAP,SHLD-USDT-SWAP,SIGN-USDT-SWAP,SIMO-USDT-SWAP,SKHY-USDT-SWAP,SKHYNIX-USDT-SWAP,SKY-USDT-SWAP,SLX-USDT-SWAP,SMCI-USDT-SWAP,SMH-USDT-SWAP,SNDK-USDT-SWAP,SNOW-USDT-SWAP,SNX-USDT-SWAP,SNXX-USDT-SWAP,SOFTBANK-USDT-SWAP,SOL-USDT-SWAP,SONY-USDT-SWAP,SOON-USDT-SWAP,SOPH-USDT-SWAP,SOXL-USDT-SWAP,SOXS-USDT-SWAP,SPACE-USDT-SWAP,SPCX-USDT-SWAP,SPK-USDT-SWAP,SPX-USDT-SWAP,SPY-USDT-SWAP,SQQQ-USDT-SWAP,SSV-USDT-SWAP,STABLE-USDT-SWAP,STRC-USDT-SWAP,STRK-USDT-SWAP,STX-USDT-SWAP,SUI-USDT-SWAP,SUSHI-USDT-SWAP,SYRUP-USDT-SWAP,TAO-USDT-SWAP,TER-USDT-SWAP,THETA-USDT-SWAP,TIA-USDT-SWAP,TQQQ-USDT-SWAP,TRB-USDT-SWAP,TRIA-USDT-SWAP,TRUMP-USDT-SWAP,TRUST-USDT-SWAP,TRUTH-USDT-SWAP,TRX-USDT-SWAP,TSEM-USDT-SWAP,TSLA-USDT-SWAP,TSM-USDT-SWAP,TTMI-USDT-SWAP,TTWO-USDT-SWAP,TURBO-USDT-SWAP,TWLO-USDT-SWAP,UB-USDT-SWAP,UMA-USDT-SWAP,UNH-USDT-SWAP,UNI-USDT-SWAP,UP-USDT-SWAP,URNM-USDT-SWAP,USAR-USDT-SWAP,USDC-USDT-SWAP,USELESS-USDT-SWAP,USO-USDT-SWAP,UVXY-USDT-SWAP,VANA-USDT-SWAP,VIRTUAL-USDT-SWAP,VRT-USDT-SWAP,VVV-USDT-SWAP,W-USDT-SWAP,WAL-USDT-SWAP,WCT-USDT-SWAP,WDC-USDT-SWAP,WEN-USDT-SWAP,WET-USDT-SWAP,WIF-USDT-SWAP,WLD-USDT-SWAP,WLFI-USDT-SWAP,WOO-USDT-SWAP,XAG-USDT-SWAP,XAU-USDT-SWAP,XBI-USDT-SWAP,XCU-USDT-SWAP,XLE-USDT-SWAP,XLM-USDT-SWAP,XPD-USDT-SWAP,XPL-USDT-SWAP,XPT-USDT-SWAP,XRP-USDT-SWAP,XTZ-USDT-SWAP,YB-USDT-SWAP,YFI-USDT-SWAP,YGG-USDT-SWAP,ZAMA-USDT-SWAP,ZBT-USDT-SWAP,ZEC-USDT-SWAP,ZEN-USDT-SWAP,ZETA-USDT-SWAP,ZHIPU-USDT-SWAP,ZIL-USDT-SWAP,ZK-USDT-SWAP,ZKP-USDT-SWAP,ZM-USDT-SWAP,ZORA-USDT-SWAP,ZRO-USDT-SWAP,ZRX-USDT-SWAP',
                BASE_TIMEFRAME_MIN: '15',
                TF_MULT: '18',
                INITIAL_CAPITAL: '253576',
                DEFAULT_LEVERAGE: '100',
                TRADE_QTY_PCT: '0.001',
                OKX_API_KEY: '92594391-3d2a-407e-9cab-bee6e8d8f4c2',
                OKX_API_SECRET: '4B9B31851E3F81B329AB2E9BB8F26E95',
                OKX_API_PASSPHRASE: 'Ya@65237365',
            },

            // 日志
            log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS',
            error_file: './logs/bot-error.log',
            out_file: './logs/bot-out.log',
            merge_logs: true,
        },
    ],
};
